version: '3'

# This file is intended for local testing and development

services:
  npc-service:
    image: ${DOCKER_REG}gta/npc${DOCKER_TAG}
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        basedir: npc
        port: 4000
    ports: 
      - 4000:4000
    env_file:
      - .env
    environment: 
      API_GOD_HOST: http://god-service:7000
      API_WORLD_HOST: http://world-service:3000
      API_PLAYER_HOST: http://player-service:5000

  god-service:
    image: ${DOCKER_REG}gta/god${DOCKER_TAG}
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        basedir: god
        port: 7000
    ports: 
      - 7000:7000
    env_file:
      - .env
    environment: 
      API_NPC_HOST: http://npc-service:4000
      API_WORLD_HOST: http://world-service:3000
      API_PLAYER_HOST: http://player-service:5000

  world-service:
    image: ${DOCKER_REG}gta/world${DOCKER_TAG}
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        basedir: world
        port: 3000
    ports: 
      - 3000:3000
    env_file:
      - .env
    environment: 
      API_GOD_HOST: http://god-service:7000
      API_NPC_HOST: http://npc-service:4000
      API_PLAYER_HOST: http://player-service:5000

  player-service:
    image: ${DOCKER_REG}gta/player${DOCKER_TAG}
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        basedir: player
        port: 5000
    ports: 
      - 5000:5000
    env_file:
      - .env
    environment: 
      API_GOD_HOST: http://god-service:7000
      API_WORLD_HOST: http://world-service:3000
      API_NPC_HOST: http://npc-service:4000  