@playerId = 18ae2215-b2ef-4300-b8a8-90d92bc19ebd

### Rename player
POST http://localhost:5000/api/players/{{playerId}}/name
content-type: application/json

{
  "newName": "Big Dave"
}

### Player Look

GET http://localhost:5000/api/players/{{playerId}}/look