@locationId = 0226d0df-c70d-465e-8543-efc180b877cf
@moveLocationId = 43cf4d0c-777a-4ab3-b0d7-c44808384585

### Create a NPC 
# @name create
POST http://localhost:4000/api/npcs/create
content-type: application/json

{
  "type": "goblin",
  "locationId": "{{locationId}}"
}

### Get new NPC id
@npcId = {{create.response.body.$.entities[0].id}}


### Get NPC  
GET http://localhost:7000/api/entities/npc/{{npcId}}

### Get ALL NPCs
GET http://localhost:7000/api/entities/npc

### Damage an NPC
POST http://localhost:4000/api/npcs/{{npcId}}/damage
content-type: application/json

{
  "value": {{$randomInt 2 8}}
}

### Teleport a NPC somewhere
POST http://localhost:4000/api/npcs/{{npcId}}/teleport
content-type: application/json

{
  "location": "{{moveLocationId}}"
}

### Walk a NPC somewhere
POST http://localhost:4000/api/npcs/60fe7b32-40bd-42e2-990c-4f166a6247d3/walk
content-type: application/json

{
  "direction": "south"
}
