### Create a NPC
# @name create
POST http://localhost:4000/api/npcs/create
content-type: application/json

{
  "type": "goblin",
  "locationId": "c7dfc9b8-27a8-4b99-b9ff-3ebe654136ae"
}

### Get new NPC id
@agentId = {{create.response.body.$.entities[0].id}}
@newLocation = 464bff8e-08d1-4631-90d2-abab98643677

### Get NPC  
GET http://localhost:4000/api/npcs/{{agentId}}

### Get ALL NPCs
GET http://localhost:4000/api/npcs

### Damage an NPC
POST http://localhost:4000/api/npcs/{{agentId}}/damage
content-type: application/json

{
  "value": {{$randomInt 2 8}}
}

### Move a NPC somewhere
PUT http://localhost:4000/api/npcs/{{agentId}}/move/464bff8e-08d1-4631-90d2-abab98643677
